# Music Recommendations Project

In [37]:
import numpy as np

# Genre Likes Matrix

In [38]:
#This matrix states whether a user likes that genre or does not like that genre.
# 0 = no, does not like that genre
# 1 = yes, does like that genre

Likes = np.matrix([[1, 0, 0, 1],
                 [0, 1, 1, 1],
                 [0, 1, 0, 1],
                 [1, 1, 0, 0]])
print("This matrix states whether a user likes that genre or does not like that genre: ")
print("0 = no, does not like that genre")
print("1 = yes, does like that genre")
print(Likes)

This matrix states whether a user likes that genre or does not like that genre: 
0 = no, does not like that genre
1 = yes, does like that genre
[[1 0 0 1]
 [0 1 1 1]
 [0 1 0 1]
 [1 1 0 0]]


# Types of Songs Matrix

In [39]:
#This matrix states how strongly alligned a song is to a genre.
# 1 = not alligned to 4 = very alligned

Types = np.matrix([[4, 3, 1, 1, 4],
                  [1, 1, 4, 2, 1],
                  [1, 1, 1, 1, 1],
                    [1, 2, 2, 4, 1]])

print("This matrix states how strongly alligned a song is to a genre: ")
print("1 = not alligned to 4 = very alligned")
print(Types)

This matrix states how strongly alligned a song is to a genre: 
1 = not alligned to 4 = very alligned
[[4 3 1 1 4]
 [1 1 4 2 1]
 [1 1 1 1 1]
 [1 2 2 4 1]]


# Predictions Using the Genre Likes and the Types of Songs Matrices

Using these two matrices, I will be performing the dot product on them to predict how a user would rate the songs.

In [40]:
ratingPredictions = np.dot(Likes, Types)

print("Predicted Ratings for Each Song on Each Person:")
print(ratingPredictions)

Predicted Ratings for Each Song on Each Person:
[[5 5 3 5 5]
 [3 4 7 7 3]
 [2 3 6 6 2]
 [5 4 5 3 5]]


From doing the dot product we are able to get rankings or in other words, how strongly a user likes that particular song. From seeing how much a user likes a particular song we can start to make predictions on what genre they like which means we are getting closer to making good song recommendations to users. 

Observations of what genres users listen to from the Dot Product:

Person A: Would be recommended songs 1, 2, and 5 <br>
Person B: Would be recommended songs 3 and 4 <br>
Person C: Would be recommended songs 3 and 4 <br>
Person D: Would be recommended song 1, 3, and 5

# Edge-Cases

These cases are for when the dot product algorithm does not work to give proper music suggestions.

<b>Case 1: Users like all of the genres.</b>

In [41]:
#This matrix states whether a user likes that genre or does not like that genre.
# 0 = no, does not like that genre
# 1 = yes, does like that genre

LikesAll = np.matrix([[1, 1, 1, 1],
                 [1, 1, 1, 1],
                 [1, 1, 1, 1],
                 [1, 1, 1, 1]])
print("This matrix states whether a user likes that genre or does not like that genre: ")
print("0 = no, does not like that genre")
print("1 = yes, does like that genre")
print(LikesAll)
print("Note that this matrix is an all-ones matrix. ")

This matrix states whether a user likes that genre or does not like that genre: 
0 = no, does not like that genre
1 = yes, does like that genre
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Note that this matrix is an all-ones matrix. 


This matrix shows that all of the users love all the genres of music that the users have available to them to listen to.

For the types of song matrix, we will use the same one as used above.

In [42]:
#This matrix states how strongly alligned a song is to a genre.
# 1 = not alligned to 4 = very alligned

Types = np.matrix([[4, 3, 1, 1, 4],
                  [1, 1, 4, 2, 1],
                  [1, 1, 1, 1, 1],
                    [1, 2, 2, 4, 1]])

print("This matrix states how strongly alligned a song is to a genre: ")
print("1 = not alligned to 4 = very alligned")
print(Types)

This matrix states how strongly alligned a song is to a genre: 
1 = not alligned to 4 = very alligned
[[4 3 1 1 4]
 [1 1 4 2 1]
 [1 1 1 1 1]
 [1 2 2 4 1]]


Recommendations Using the Dot Product:

In [43]:
ratingPredictions = np.dot(LikesAll, Types)

print("Predicted Ratings for Each Song on Each Person:")
print(ratingPredictions)

Predicted Ratings for Each Song on Each Person:
[[7 7 8 8 7]
 [7 7 8 8 7]
 [7 7 8 8 7]
 [7 7 8 8 7]]


As you can see from this matrix above, the dot product cannot give proper suggestions if all of the users like all of the available music genres available to them. 

<b>Case 2: Users like none of the genres.</b>

In [44]:
#This matrix states whether a user likes that genre or does not like that genre.
# 0 = no, does not like that genre
# 1 = yes, does like that genre

LikesNone = np.matrix([[0, 0, 0, 0],
                 [0, 0, 0, 0],
                 [0, 0, 0, 0],
                 [0, 0, 0, 0]])
print("This matrix states whether a user likes that genre or does not like that genre: ")
print("0 = no, does not like that genre")
print("1 = yes, does like that genre")
print(LikesNone)
print("Note that this is an all-zero matrix.")

This matrix states whether a user likes that genre or does not like that genre: 
0 = no, does not like that genre
1 = yes, does like that genre
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Note that this is an all-zero matrix.


This matrix shows that all of the users do not like any of the genres of music that the users have available to them to listen to.

For the types of song matrix, we will use the same one as used above.

In [45]:
#This matrix states how strongly alligned a song is to a genre.
# 1 = not alligned to 4 = very alligned

Types = np.matrix([[4, 3, 1, 1, 4],
                  [1, 1, 4, 2, 1],
                  [1, 1, 1, 1, 1],
                    [1, 2, 2, 4, 1]])

print("This matrix states how strongly alligned a song is to a genre: ")
print("1 = not alligned to 4 = very alligned")
print(Types)

This matrix states how strongly alligned a song is to a genre: 
1 = not alligned to 4 = very alligned
[[4 3 1 1 4]
 [1 1 4 2 1]
 [1 1 1 1 1]
 [1 2 2 4 1]]


Recommendations Using the Dot Product:

In [46]:
ratingPredictions = np.dot(LikesNone, Types)

print("Predicted Ratings for Each Song on Each Person:")
print(ratingPredictions)

Predicted Ratings for Each Song on Each Person:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


As you can see from this matrix above, the dot product cannot give proper suggestions if all of the users do not like any of the available music genres available to them. 

# When does the dot product work best?

<b>Case 1: Each song only alligns to one song.</b> <br>
In this case, each song will only be alligned to one genre in the Genre Likes Matrix.

In [47]:
#This matrix states how strongly alligned a song is to a genre.
# 1 = not alligned to 4 = very alligned

TypesOneGenre = np.matrix([[4, 1, 1, 1, 4],
                  [1, 4, 1, 1, 1],
                  [1, 1, 4, 1, 1],
                    [1, 1, 1, 4, 1]])

print("This matrix states how strongly alligned a song is to a genre: ")
print("1 = not alligned to 4 = very alligned")
print(TypesOneGenre)

This matrix states how strongly alligned a song is to a genre: 
1 = not alligned to 4 = very alligned
[[4 1 1 1 4]
 [1 4 1 1 1]
 [1 1 4 1 1]
 [1 1 1 4 1]]


In the next matrix, Genre Likes Matrix, we will keep this matrix the same as above.

In [48]:
#This matrix states whether a user likes that genre or does not like that genre.
# 0 = no, does not like that genre
# 1 = yes, does like that genre

Likes = np.matrix([[1, 0, 0, 1],
                 [0, 1, 1, 1],
                 [0, 1, 0, 1],
                 [1, 1, 0, 0]])
print("This matrix states whether a user likes that genre or does not like that genre: ")
print("0 = no, does not like that genre")
print("1 = yes, does like that genre")
print(Likes)

This matrix states whether a user likes that genre or does not like that genre: 
0 = no, does not like that genre
1 = yes, does like that genre
[[1 0 0 1]
 [0 1 1 1]
 [0 1 0 1]
 [1 1 0 0]]


From this matrix we know: <br>
Person A: likes country and rock <br>
Person B: likes hip-hop, rap, and rock <br>
Person C: likes hip-hop and rock <br>
Person D: likes country and hip-hop

Recommendations Using the Dot Product:

In [49]:
ratingPredictions = np.dot(Likes, TypesOneGenre)

print("Predicted Ratings for Each Song on Each Person:")
print(ratingPredictions)

Predicted Ratings for Each Song on Each Person:
[[5 2 2 5 5]
 [3 6 6 6 3]
 [2 5 2 5 2]
 [5 5 2 2 5]]


From this matrix, we can confirm that the song rating predictions do allign to what genres the users like to listen to.

<b>Case 2: Each person only listens to one genre.</b> <br>
In this case, each person will only be assigned to one genre in the Genre Likes Matrix.

In [50]:
#This matrix states whether a user likes that genre or does not like that genre.
# 0 = no, does not like that genre
# 1 = yes, does like that genre

LikesOnlyOne = np.matrix([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
print("This matrix states whether a user likes that genre or does not like that genre: ")
print("0 = no, does not like that genre")
print("1 = yes, does like that genre")
print(LikesOnlyOne)

This matrix states whether a user likes that genre or does not like that genre: 
0 = no, does not like that genre
1 = yes, does like that genre
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Note: This is the identity matrix, which makes this case of users only like one type of song as you will see in the end of this case.

In the next matrix, Types of Songs Matrix, we will keep this matrix the same as above.

In [51]:
#This matrix states how strongly alligned a song is to a genre.
# 1 = not alligned to 4 = very alligned

Types = np.matrix([[4, 3, 1, 1, 4],
                  [1, 1, 4, 2, 1],
                  [1, 1, 1, 1, 1],
                    [1, 2, 2, 4, 1]])

print("This matrix states how strongly alligned a song is to a genre: ")
print("1 = not alligned to 4 = very alligned")
print(Types)

This matrix states how strongly alligned a song is to a genre: 
1 = not alligned to 4 = very alligned
[[4 3 1 1 4]
 [1 1 4 2 1]
 [1 1 1 1 1]
 [1 2 2 4 1]]


Recommendations Using the Dot Product:

In [52]:
ratingPredictions = np.dot(LikesOnlyOne, Types)

print("Predicted Ratings for Each Song on Each Person:")
print(ratingPredictions)

Predicted Ratings for Each Song on Each Person:
[[4 3 1 1 4]
 [1 1 4 2 1]
 [1 1 1 1 1]
 [1 2 2 4 1]]


As you can see above, since the identity matrix is used the predictions are going to be identitical to the Types of Songs Matrix. This means that each person will be recommended the song that most strongly correlates to the only genre they listen to. 

Example: For Person A, they would be strongly recommended Songs one and five because they are fully country whereas song two would also be recommended but slightly less.